version: "3.8"

services:
  server: 
    image: game-server
    networks:
      - game-server
    ports:
      - "27015:27015/udp"
    env_file:
      - .env
    depends_on:
      postgres: 
        condition: service_healthy

  postgres:
    image: 'postgres:15'
    networks:
      - game-server
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=local
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
    healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${POSTGRES_DB}'
                - '-U'
                - '${POSTGRES_USER}'
            retries: 3
            timeout: 5s
  redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - 'game-server-redis:/data'
        networks:
            - game-server
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

networks:
    game-server:
        driver: bridge

volumes:
    game-server-redis:
        driver: local