name: Development Build and Release 

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: development

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1.8.0
        with:
          token: ${{ github.token }}
          branch: develop

      - name: Create Draft Release
        uses: ncipollo/release-action@v1.14.0
        with:
          prerelease: true
          draft: false
          commit: ${{ github.sha }}
          tag: ${{ steps.semver.outputs.next }}-dev
          name: ${{ steps.semver.outputs.next }}-dev
          body: '*pending*'
          token: ${{ github.token }}

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1.10.2
        with:
          token: ${{ github.token }}
          tag: ${{ steps.semver.outputs.next }}
          writeToFile: false

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          tag: ${{ steps.semver.outputs.next }}-dev
          name: ${{ steps.semver.outputs.next }}-dev
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}